### ISSUE TITLE
Improper naming of variables

### ISSUE THREAD

**Issue by atom-dispencer** [GenElectrovise/MagiksMostEvile#27]
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

_Originally posted by @aimiebell in https://github.com/GenElectrovise/MagiksMostEvile/pull/24#discussion_r572617636_

**Comment by atom-dispencer** [comment]
Hi, @aimiebell - thanks for the comment.
Which method names do you mean? I see no _method calls_ in your code snippet, just _public static final constants_ in accordance with:

"The names of variables declared class constants and of ANSI constants should be all uppercase with words separated by underscores ("_"). (ANSI constants should be avoided, for ease of debugging.)"
(https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html)

**Comment by cal101** [comment]
I found such a wrong comment on some pull request of mine, too.
I took a look at the user and it looks like a kind of code troll IMO.
Interesting that you follow him on github.

**Comment by atom-dispencer** [comment]
Yeah I followed thinking that there would be a following conversation (thought that they were making a valid comment maybe?)

Given that it sounds like a troll I'll just unfollow now. Thx for letting me know.
